# Generated by Django 4.1.1 on 2022-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=1)),
                ('nama', models.CharField(max_length=20)),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
